### ISSUE TITLE
Admin offer grid filter

### ISSUE THREAD

**Issue by AymericJoubert** [Smile-SA/magento2-module-offer#1]
In backoffice, on offer listing grid. When adding an offer id on "from" filter and validating filters, the grid crashes and stay locked on loading image.
We have to remove the good line in ui_bookmark sql table to remove the stored filter and get the grid working again.

The bug seems to come from the Smile\Offer\Model\ResourceModel\Offer\Grid\Collection::addHasOverlapField() method. Commenting lines 222 to 226 solves the issue.

**Comment by romainruaud** [comment]
Closing due to being outdated.
