### ISSUE TITLE
Exception on Catalog page because offer.price facet is not an array

### ISSUE THREAD

**Issue by lucasmilin** [Smile-SA/magento2-module-offer#10]
Magento 2.3.1
ElasticSuite: 2.7
Mode: Drive

File where exception happened: vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php

Line 299:
public function addFacet($facetConfig)
    {
        $this->facets[$facetConfig['name']] = $facetConfig;
        
        return $this;
    }

Output of debugging $facetConfig:

Array
(
    [type] => queryGroupBucket
    [name] => categories
    [queries] => Array
        (
        )

)
Array
(
    [name] => name
    [type] => termBucket
    [size] => 10
    [sortOrder] => _count
)

String
offer.price

This causes an exception #0 (Exception): Warning: Illegal string offset 'name'

**Comment by Fdec** [comment]
Fix on last branch.
