### ISSUE TITLE
Backoffice - Wrong product name in collection

### ISSUE THREAD

**Issue by ThibautO** [Smile-SA/magento2-module-offer#11]
### Preconditions

Magento Version : 2.3.2 EE
Module Offer Version : 1.3.4
Environment : Developer
Third party modules : Smile_Retailer, Smile_RetailerOffer, Smile_Seller

### Steps to reproduce
1. Create (or having) a product having its row_id different than its entity_id (table 'catalog_product_entity')
2. Create an offer for the previous product
3. Go on Retailer Offers List in backoffice

### Expected result
1. We should have product name in offer listing

### Actual result
1. We have the name of another product

### Some informations
When retrieving product information for listing purpose, we are using 'entity_id' field of the product. But the product 'name' is stocked in table 'catalog_product_entity_varchar', and is identified by product 'row_id'.

Whenever a product does not have the same value for fields 'row_id' and 'entity_id', we are loading the name of another product.

**Comment by Fdec** [comment]
Wrong module, I duplicate in https://github.com/Smile-SA/magento2-module-retailer-offer

**Comment by Fdec** [comment]
hi @ThibautO 

See this link https://magento.stackexchange.com/questions/278051/row-id-vs-entity-id-in-magento-2-3-ee 

'row_id' is in EE version.
