### ISSUE TITLE
Make offer grid collection compatible with staging.

### ISSUE THREAD

**Issue by afoucret** [Smile-SA/magento2-module-offer#5]
Bug into `Model/ResourceModel/Offer/Grid/Collection.php`
Attribute join uses `entity_id` instead of `row_id`

**Comment by romainruaud** [comment]
For me this was fixed by : https://github.com/Smile-SA/magento2-module-offer/commit/e5b2cf9ad81d887472bad5e13279672d0aa406d3

The only usage of entity_id is for SKU retrieval directly on the catalog_product_entity table, which should be correct.

No ?

**Comment by delyriand** [comment]
Hi @afoucret,

Is @romainruaud  right and the issue is fixed via commit e5b2cf9?

**Comment by romainruaud** [comment]
For me, the given commit is enough to fix it. Try on an EE version to ensure grid is not broken, but should work properly.

**Comment by delyriand** [comment]
I confirm that I have no problem to display offers grid on a magento / product-enterprise-edition 2.2.5
